import { BOT_DESCRIPTIONS, DEFAULT_BOT_POLICY, effectiveToolPolicy, type BotPolicy, type BotSnapshot } from "./bot-schema.js";
import type { PipelineRun } from "./pipeline.js";
import { BOT_PROFILES } from "./bot-profiles.js";

const escape = (value: string | number) => String(value).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
export function botTimeline(bots: BotSnapshot, run: PipelineRun, selectedPhase?: number): string {
  const phase = selectedPhase !== undefined && run.config.stages[selectedPhase] ? selectedPhase : run.current;
  const definition = run.config.stages[phase]!;
  const policy: BotPolicy = definition.bot ?? DEFAULT_BOT_POLICY;
  const tools = effectiveToolPolicy(policy);
  const profile = policy.profile ? BOT_PROFILES[policy.profile] : undefined;
  const attempts = bots.attempts.filter(item => item.runId === run.id && item.stageId === definition.id);
  const attempt = attempts.at(-1);
  const active = run.current === phase && run.status === "running" && run.stages[phase]!.status === "active";
  const ready = attempt && ["ready", "applied"].includes(attempt.status) && attempt.revision === run.revision && active;
  return `<section class="bot-workspace" aria-label="Bot timeline"><div class="bot-section-heading"><div><p class="eyebrow">BOT TIMELINE</p><h3>The right bot, at each phase.</h3></div><span class="pipeline-chip">${bots.busy ? "Bot working" : "You control the handoff"}</span></div>
    <ol class="bot-timeline">${run.config.stages.map((item, index) => {
      const kind = item.bot?.kind ?? "manual";
      const count = bots.attempts.filter(attempt => attempt.runId === run.id && attempt.stageId === item.id).length;
      return `<li class="${run.stages[index]!.status}"><button data-bot-phase="${index}" aria-pressed="${index === phase}"><span class="bot-step">${index + 1}</span><strong>${escape(item.name)}</strong><span>${escape(kind)}${kind === "manual" ? " handoff" : " bot"}</span><small>${escape(item.model)}</small><small>${escape(run.stages[index]!.status.replaceAll("_", " "))} · ${count} attempts</small></button></li>`;
    }).join("")}</ol>
    <div class="bot-phase"><div><span class="eyebrow">${escape(definition.name)}</span><h3>${escape(definition.agent)}</h3><p>${escape(profile?.purpose ?? BOT_DESCRIPTIONS[policy.kind])}</p>${profile ? `<p class="muted">Agent profile: ${escape(profile.name)} · Expected handoff: ${profile.sections.map(escape).join(" · ")}</p>` : ""}<p>${escape(definition.instructions)}</p><div class="bot-facts"><span>Model: ${escape(definition.model)}</span><span>${policy.maxSteps} model calls maximum</span><span>${policy.timeoutSeconds}s limit</span><span>${tools.maxToolCalls} MCP calls maximum</span><span>${definition.approval ? "Independent approval required" : "Operator handoff"}</span></div><p class="muted">Inputs: ${escape(definition.context)} and completed phase outputs.</p><p class="muted">Tools: ${policy.kind === "manual" ? "Manual evidence" : escape(tools.allowedTools.join(", ") || "No repository tools")}${policy.kind === "coder" ? "; propose up to five file changes" : ""}.</p></div>
      ${active && policy.kind !== "manual" ? `<button class="primary" data-bot-action="start" ${bots.busy || !bots.project ? "disabled" : ""}>${profile ? `Run ${escape(profile.name)}` : `Run ${escape(policy.kind)} bot`}</button><p class="muted">Selected source files are sent to this phase's configured model. Review its provider before running.</p>` : `<p class="muted">${policy.kind === "manual" ? "Assign a bot in Configurables, then start a new run to use that configuration." : run.stages[phase]!.status === "complete" ? "This phase is complete. Its recorded evidence remains available below." : run.status === "cancelled" ? "This session was cancelled. Its recorded evidence remains available below." : "This phase is waiting for the session to resume or for preceding handoffs and approvals."}</p>`}
      ${attempt ? `<article class="bot-result"><div class="bot-section-heading"><h4>Latest attempt · ${escape(attempt.status)}</h4><small>${escape(new Date(attempt.startedAt).toLocaleString())}</small></div><p class="muted">Checkout: <code>${escape(attempt.checkout)}</code></p><button class="secondary" data-bot-copy="${escape(attempt.checkout)}">Copy path for your editor</button><p class="muted">Base commit ${escape(attempt.baseCommit.slice(0, 12))} · ${attempt.calls} model calls · Tokens and cost: unavailable</p>
      ${attempt.error ? `<p class="form-error" role="alert">${escape(attempt.error)}</p>` : ""}${attempt.summary ? `<pre>${escape(attempt.summary)}</pre>` : ""}
      ${attempt.handoff ? `<section aria-label="Agent handoff"><h4>Agent handoff</h4><p class="muted">Agent-authored report. Recorded command results are shown separately.</p>${attempt.handoff.sections.map(section => `<h4>${escape(section.title)}</h4><pre>${escape(section.body)}</pre>`).join("")}${attempt.handoff.blockers.length ? `<div class="form-error" role="alert"><strong>Handoff blocked</strong><ul>${attempt.handoff.blockers.map(blocker => `<li>${escape(blocker)}</li>`).join("")}</ul><p>Resolve these items and run a new attempt.</p></div>` : ""}</section>` : ""}
      ${attempt.changes.map(change => `<details class="bot-change"><summary>${escape(change.path)} · ${change.before === null ? "New file" : "Proposed replacement"}</summary><div class="bot-diff"><div><h4>Before</h4><pre>${escape(change.before ?? "(new file)")}</pre></div><div><h4>After</h4><pre>${escape(change.after)}</pre></div></div></details>`).join("")}
      ${attempt.checks.map(check => `<details><summary>${check.passed ? "Passed" : "Failed"} · ${escape(check.command.executable)} ${escape(check.command.args.join(" "))} · exit ${check.exitCode ?? "unavailable"}</summary><pre>${escape(check.output)}</pre></details>`).join("")}
      <div class="pipeline-actions">${attempt.status === "running" ? `<button class="secondary" data-bot-action="cancel" data-bot-attempt="${attempt.id}" data-bot-hash="${attempt.proposalHash}">Stop bot</button>` : ""}
      ${ready && !bots.busy ? `${attempt.changes.length && attempt.status === "ready" ? `<button class="secondary" data-bot-action="apply" data-bot-attempt="${attempt.id}" data-bot-hash="${attempt.proposalHash}">Apply reviewed changes</button>` : ""}<button class="secondary" data-bot-action="checks" data-bot-attempt="${attempt.id}" data-bot-hash="${attempt.proposalHash}" ${bots.project?.checks.length ? "" : "disabled"}>Run configured checks</button><button class="primary" ${attempt.handoff?.blockers.length ? "disabled" : ""} data-bot-action="accept" data-bot-attempt="${attempt.id}" data-bot-hash="${attempt.proposalHash}">${definition.approval ? "Submit bot result for review" : "Accept result & hand off"}</button>` : ""}</div>
      <details><summary>Attempt log · ${attempt.events.length} events</summary>${attempt.events.map(event => `<p><small>${escape(new Date(event.at).toLocaleTimeString())}</small> ${escape(event.message)}</p>`).join("")}</details>
      ${attempts.length > 1 ? `<details><summary>Earlier attempts</summary>${attempts.slice(0, -1).reverse().map(item => `<p>${escape(item.startedAt)} · ${escape(item.status)} · ${escape(item.summary || item.error)}</p>`).join("")}</details>` : ""}</article>` : '<p class="muted">No bot has run for this phase yet.</p>'}
    </div></section>`;
}

export function projectView(bots: BotSnapshot): string {
  if (bots.project) return `<details class="bot-project"><summary>Developer environment · ${escape(bots.project.root)}</summary><p>Magentic works beside your existing editor. Each run starts an isolated checkout from committed HEAD; your current checkout and unsaved edits stay in place.</p><p>Checks: ${bots.project.checks.length ? bots.project.checks.map(check => `<code>${escape(check.executable)} ${escape(check.args.join(" "))}</code>`).join(" · ") : "None configured"}</p><p class="muted">Check commands run with your OS account in the isolated checkout. Git isolation is not an OS sandbox. Open the checkout path in your editor to inspect or integrate the result.</p></details>`;
  return `<details class="bot-project" open><summary>Connect your developer environment</summary><p>Attach an existing Git repository. Keep using your editor, languages, and build tools.</p><form id="bot-project-form"><label>Repository root<input name="root" required placeholder="C:\\projects\\my-app or /home/me/my-app"></label><label>Validation commands · JSON array<textarea name="checks" rows="3" spellcheck="false">[]</textarea></label><small>Example: [{"executable":"node","args":["--test"]}]. Commands run only when you click Run configured checks, using your OS account. Use executables, not shell syntax. Start with [] for planning.</small><button class="secondary" type="submit">Attach repository</button></form></details>`;
}
