import type { ChatAvailability, ChatMessage, ChatModelOption } from "./chat.js";

export interface ChatTurn extends ChatMessage { model?: string; tools?: { name: string; state: string }[]; /** Who answered: a chatbot profile's name, or absent for the workspace assistant. */ assistant?: string }
export interface ChatProfileOption { id: string; name: string; release: string }
export interface ChatState {
  options: ChatModelOption[]; models: string[]; selectedModel: string; loadingModels: boolean;
  /** A Model Studio chatbot profile id, or "" for the plain workspace assistant. */
  profile: string;
  messages: ChatTurn[]; draft: string; busy: boolean; phase: string; error: string;
  tools: { name: string; state: string }[];
}
export function emptyChat(): ChatState {
  return { options: [], models: [], selectedModel: "", loadingModels: false, profile: "", messages: [], draft: "", busy: false, phase: "", error: "", tools: [] };
}
const escape = (value: string) => value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
function toolActivity(tools: { name: string; state: string }[]): string {
  return tools.map((tool) => `<span class="chat-tool"><span aria-hidden="true">${tool.state === "done" ? "✓" : tool.state === "failed" ? "!" : "◷"}</span> ${escape(tool.name)} · ${escape(tool.state)}</span>`).join("");
}
/** `locked` hides the assistant picker: the page around the chat already chose the assistant. */
export function chatView(config: ChatAvailability, state: ChatState, profiles: ChatProfileOption[] = [], view: { locked?: boolean; base?: boolean } = {}): string {
  const selectedModel = state.selectedModel || config.model || "";
  const profile = profiles.find((item) => item.id === state.profile);
  const models = state.models.length ? state.models : selectedModel ? [selectedModel] : [];
  const options = state.options.length ? state.options : models.map((id) => ({ id, label: id,
    provider: config.provider ?? "Models", available: config.configured, local: config.provider === "ollama", detail: "" }));
  const selected = options.find((model) => model.id === selectedModel);
  // A profile chosen earlier whose release has since been retired, rejected
  // or disabled is no longer offered. Sending would be refused by the
  // server; the page says so first and does not offer to send.
  const staleProfile = !!state.profile && !profile;
  const disabled = state.busy || state.loadingModels || !config.configured || selected?.available === false || staleProfile;
  const groups = [...new Set(options.map((model) => model.provider))];
  const baseToolbar = `<div class="base-chat-toolbar"><div class="base-model"><label for="chat-model"><span class="visually-hidden">Model</span><select id="chat-model" ${state.busy || state.loadingModels ? "disabled" : ""}>${groups.map((group) => `<optgroup label="${escape(group)}">${options.filter((model) => model.provider === group).map((model) => `<option value="${escape(model.id)}" ${model.id === selectedModel ? "selected" : ""}>${escape(model.label)}${model.available ? "" : " · connection required"}</option>`).join("")}</optgroup>`).join("") || '<option>No models available</option>'}</select></label><span class="base-model-location">${selected?.available ? selected.local ? "Local" : escape(selected.provider) : "Not connected"}</span></div><div class="base-chat-controls"><button class="secondary" id="new-chat">＋ New chat</button><details class="base-chat-options"><summary aria-label="Chat options" title="Chat options">⋯</summary><div><button class="secondary" id="refresh-models" ${state.busy || state.loadingModels || !config.configured ? "disabled" : ""}>${state.loadingModels ? "Loading…" : "Refresh models"}</button><small>Chats stay in this tab until you reload.</small></div></details></div></div>`;
  return `${view.base ? baseToolbar : `<div class="chat-toolbar"><div><span class="chat-model-dot"></span><strong>${profile ? escape(profile.name) : view.base ? "Magentic Chat" : "Workspace assistant"}</strong><small>${escape(selected?.provider ?? "Model not configured")} · ${escape(selected?.label ?? selectedModel)}${profile ? ` · ${escape(profile.release)}` : ""}</small></div><button class="secondary" id="new-chat">＋ New chat</button></div>`}
    ${(profiles.length || state.profile) && !view.locked && !view.base ? `<div class="chat-model-picker"><label for="chat-profile">Assistant<select id="chat-profile" ${state.busy ? "disabled" : ""}>${staleProfile ? '<option value="" disabled selected>Unavailable profile</option>' : ""}<option value="" ${state.profile ? "" : "selected"}>Magentic workspace assistant</option>${profiles.map((item) => `<option value="${escape(item.id)}" ${item.id === state.profile ? "selected" : ""}>${escape(item.name)} · ${escape(item.release)}</option>`).join("")}</select></label><small>${profile ? "Approved release. Its instructions apply on top of the selected model. A development artifact carries no trained weights." : "Profiles come from approved Model Studio releases."}</small></div>` : ""}
    ${staleProfile ? '<div class="chat-setup" role="alert"><strong>This chatbot profile is no longer available.</strong><p>Its release was retired or the profile was disabled. Choose another assistant to continue.</p></div>' : ""}
    ${view.base ? "" : `<div class="chat-model-picker"><label for="chat-model">Model<select id="chat-model" ${state.busy || state.loadingModels ? "disabled" : ""}>${groups.map((group) => `<optgroup label="${escape(group)}">${options.filter((model) => model.provider === group).map((model) => `<option value="${escape(model.id)}" ${model.id === selectedModel ? "selected" : ""}>${escape(model.label)}${model.available ? "" : " · connection required"}</option>`).join("")}</optgroup>`).join("") || '<option>No models available</option>'}</select></label><button class="secondary" id="refresh-models" ${state.busy || state.loadingModels || !config.configured ? "disabled" : ""}>${state.loadingModels ? "Loading…" : "↻ Refresh models"}</button><small>${options.length} choices · ${options.filter((model) => model.available).length} configured</small></div>`}
    ${selected && !selected.available ? `<div class="chat-setup" role="status"><strong>Connect ${escape(selected.provider)}</strong><p>${escape(selected.detail)} Your draft stays here while you choose another model.</p></div>` : !config.configured ? '<div class="chat-setup"><strong>Connect a model to start chatting.</strong><p>Configure MAGENTIC_LLM_PROVIDER and MAGENTIC_LLM_CHAT_MODEL on the server, then restart.</p></div>' : ""}
    ${selected?.available && (!view.base || !selected.local) ? `<p class="chat-destination">${selected.local ? "Runs through your Ollama server." : `Sending uses ${escape(selected.provider)} and includes ${view.base ? "this conversation" : "this conversation and any MCP results needed to answer"}. API usage may incur charges.`} ${view.base ? "" : "Selection applies to the next message."}</p>` : ""}
    <div class="chat-transcript" role="log" aria-label="Conversation" aria-live="polite">
      ${state.messages.length ? state.messages.map((message) => `<article class="chat-message ${message.role}"><div class="chat-avatar" aria-hidden="true">${message.role === "assistant" ? (view.base ? "◆" : "m") : "You"}</div><div class="chat-message-content"><strong>${message.role === "assistant" ? escape(message.assistant ?? "Magentic") : "You"}</strong>${message.model && (!view.base || message.model !== selectedModel) ? `<small class="chat-reply-model">${escape(message.model)}</small>` : ""}<div class="chat-text">${escape(message.content)}</div>${message.tools?.length ? `<details class="chat-evidence"><summary>Used ${message.tools.length} MCP ${message.tools.length === 1 ? "tool" : "tools"}</summary>${toolActivity(message.tools)}</details>` : ""}</div></article>`).join("") : `${view.base ? `<div class="chat-welcome"><span class="base-chat-diamond" aria-hidden="true">◆</span><h2>What can I help with?</h2><div class="chat-starters"><button data-base-prompt="Help me draft a clear update for my team." ${disabled ? "disabled" : ""}><span>Draft an update</span></button><button data-base-prompt="Explain this in plain language: " ${disabled ? "disabled" : ""}><span>Explain something</span></button><button data-base-prompt="Help me turn this goal into a practical plan: " ${disabled ? "disabled" : ""}><span>Make a plan</span></button></div></div>` : profile ? `<div class="chat-welcome"><p class="text-2">${escape(profile.name)} answers under ${escape(profile.release)}. Its instructions apply on top of the selected model; no trained weights are involved.</p></div>` : `<div class="chat-welcome"><p class="text-2">Ask about approved agents or the approval policy. Answers come from read only MCP tools.</p><div class="chat-starters"><button data-chat-prompt="Which approved agents can I use?" ${disabled ? "disabled" : ""}><span>List approved agents</span><small>What is approved and available</small></button><button data-chat-prompt="Explain the approval policy in this workspace." ${disabled ? "disabled" : ""}><span>Explain the approval policy</span><small>What it takes to approve an agent</small></button></div></div>`}`}
      ${state.busy ? `<div class="chat-progress" role="status"><span class="chat-thinking" aria-hidden="true">● ● ●</span> ${escape(state.phase)}<div>${toolActivity(state.tools)}</div></div>` : ""}
      ${state.error ? `<div class="chat-error" role="alert">${escape(state.error)}${state.messages.at(-1)?.role === "user" && !state.busy ? '<button class="secondary" id="retry-chat">Try again</button>' : ""}</div>` : ""}
    </div>
    <form id="chat-form" class="chat-composer"><label for="chat-input"${view.base ? ' class="visually-hidden"' : ""}>Message ${profile ? escape(profile.name) : "Magentic"}</label><textarea id="chat-input" name="message" rows="${view.base ? 2 : 3}" maxlength="4000" placeholder="${profile ? `Ask ${escape(profile.name)}…` : view.base ? "Message Magentic…" : "Ask Magentic about your workspace…"}" ${disabled ? "disabled" : ""}>${escape(state.draft)}</textarea><div class="chat-composer-actions"><small title="Enter to send · Shift + Enter for a new line">${view.base ? "Shift + Enter for a new line" : "Enter to send · Shift + Enter for a new line"}</small>${state.busy ? '<button type="button" class="secondary" id="stop-chat">■ Stop</button>' : `<button class="primary" type="submit" aria-label="Send message" ${disabled ? "disabled" : ""}>${view.base ? "Send ↑" : "Send message ↑"}</button>`}</div></form>
    <div class="chat-footnote">${view.base ? "No workspace tools · Check important answers" : `${selected?.local ? "Local model" : "Hosted model"} · MCP tools are read only · Replies can be wrong; check the tool results.`}</div>`;
}
